# Logo downloaded here: https://www.vectorstock.com/royalty-free-vector/download-icon-for-web-app-logo-ui-vector-27559318
# Full code comments is generated by Claude.ai


# Import necessary libraries
from pytubefix import YouTube, Playlist
import customtkinter as ctk
from PIL import Image, ImageTk
from requests import get
from os import environ
import webbrowser
from threading import Thread
from CTkMessagebox import CTkMessagebox
from logo import path

# Define VideoBox class to represent individual video items in the UI
class VideoBox(ctk.CTkFrame):
    def __init__(self, master, Video_url):
        super().__init__(master=master, fg_color="#181818", height=120, bg_color="transparent")
        self.pack(expand=True, fill="x", padx=3, pady=2)
        self.pack_propagate(False)
        
        # Initialize video information
        self.video = YouTube(Video_url)
        self.thumbnail_url = self.video.thumbnail_url
        self.title = self.video.title
        
        # Set up thumbnail image
        self.image = Image.open(get(self.thumbnail_url, stream=True).raw).resize((160, 90))
        self.tk_image = ImageTk.PhotoImage(self.image)
        self.image_button = ctk.CTkButton(self, text="", image=self.tk_image, corner_radius=0, fg_color="#222222", hover_color="gray", command=lambda: webbrowser.open(Video_url))
        self.image_button.pack(side="left", padx=10)
        
        # Initialize other variables
        self.check = ctk.BooleanVar(value=True)
        self.streambox_value = []
        self.resolution = {}
        
        # Populate stream options
        try:
            for stream in self.video.streams.filter(file_extension="mp4"):
                name = str(stream)
                self.resolution[name] = stream
                self.streambox_value.append(name)
        except Exception as e:
            self.title = str(e)
        
        self.stream = None
        self.detail_frame_setup()

    # Callback for stream selection
    def callback1(self, event):
        self.stream = self.resolution[event]
        self.dowloadbutton.configure(state=ctk.NORMAL)
    
    # Set up the detail frame with video information and controls
    def detail_frame_setup(self):
        self.detail_frame = ctk.CTkFrame(self, fg_color="transparent")
        self.detail_frame.pack(side="left", fill="both", expand=True)
        
        # Video title
        ctk.CTkEntry(self.detail_frame,
                     textvariable=ctk.StringVar(value=self.title),
                     state="readonly",
                     font=("Arial", 20),
                     fg_color="transparent",
                     corner_radius=0,
                     border_width=0).pack(fill="x", pady=10)
        
        # Checkbox for selection
        self.checkbox = ctk.CTkCheckBox(self.detail_frame, text="", hover_color="gray", variable=self.check)
        self.checkbox.pack(side="left", padx=7)
        
        # Stream selection dropdown
        self.stream_box = ctk.CTkComboBox(self.detail_frame, state="readonly", command=self.callback1)
        self.stream_box.configure(values=self.streambox_value)
        self.stream_box.pack(side="right", expand=True, fill="x", padx=10)
        
        # Download button
        self.dowloadbutton = ctk.CTkButton(self.detail_frame,
                                           text="📥",
                                           fg_color="#222222",
                                           hover_color="gray",
                                           font=("Arial", 16), 
                                           width=20,
                                           state=ctk.DISABLED,
                                           command=lambda: Thread(target=lambda: self.stream.download()).start())
        
        # Delete button
        self.deletebutton = ctk.CTkButton(self.detail_frame, text="❌", fg_color="#222222", hover_color="gray", font=("Arial", 16), width=20, command=self.destroy)
        self.dowloadbutton.pack(side="right")
        self.deletebutton.pack(side="right")

    # Method to handle download
    def download(self):
        if self.check.get() == True:
            if self.stream != None:
                Thread(target=self.stream.download).start()
            else:
                Thread(target=self.video.streams.get_highest_resolution().download).start()
                        
    # Method to handle deletion
    def delete(self):
        if self.check.get() == True:
            self.destroy()

# Main application class
class YoutubeDownloader(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title("Youtube Downloader")
        self.geometry("900x450")
        self.iconbitmap(path)
        self.minsize(900, 450)
        self.rowconfigure(0, weight=1, uniform="a")
        self.rowconfigure(1, weight=5, uniform="a")
        self.columnconfigure(0, weight=1, uniform="a")
    
    # Set up the toolbar
    def toolframe(self):
        self.tool_frame = ctk.CTkFrame(self, fg_color="#222222", corner_radius=0)
        self.tool_frame.grid(row=0, sticky="news")      
        
        # Download all button
        self.download_button = ctk.CTkButton(self.tool_frame,
                                             text="📥",
                                             fg_color="#222222",
                                             hover_color="gray",
                                             font=("Arial", 28), 
                                             width=40, height=40,
                                             border_color="gray",
                                             border_width=2,
                                             corner_radius=0,
                                             command=self.download_func)
        self.download_button.pack(side="left", padx=15)
        
        # Delete all button
        self.delete_button = ctk.CTkButton(self.tool_frame,
                                           text="❌",
                                           fg_color="#222222",
                                           hover_color="gray",
                                           font=("Arial", 28), 
                                           width=40,
                                           height=40,
                                           border_color="gray",
                                           border_width=2,
                                           corner_radius=0,
                                           command=self.delete_func)
        self.delete_button.pack(side="left", padx=15)
        
        # Add video button
        self.add_button = ctk.CTkButton(self.tool_frame,
                                        text="➕",
                                        fg_color="#222222",
                                        hover_color="gray",
                                        font=("Arial", 28), 
                                        width=40, height=40,
                                        border_color="gray",
                                        border_width=2,
                                        corner_radius=0,
                                        command=AddURL)
        self.add_button.pack(side="left", padx=15)

        # Multi-link button
        self.multilink = ctk.CTkButton(self.tool_frame,
                                       text="📃",
                                       fg_color="#222222",
                                       hover_color="gray",
                                       font=("Arial", 28), 
                                       width=40,
                                       height=40,
                                       border_color="gray",
                                       border_width=2,
                                       corner_radius=0,
                                       command=MultiLink)
        self.multilink.pack(side="left", padx=15)
    
    # Delete all videos
    def delete_func(self):
        for box in self.list_frame.winfo_children():
            box.delete()
    
    # Download all videos
    def download_func(self):
        for box in self.list_frame.winfo_children():
            box.download()
    
    # Set up the list frame for video items
    def listframe(self):
        self.list_frame = ctk.CTkScrollableFrame(self, fg_color="transparent")
        self.list_frame.grid(row=1, sticky="news")
    
    # Add a new video to the list
    def addvideo(self, url):
        Thread(target=lambda: VideoBox(self.list_frame, url)).start()
    
    # Run the application
    def run(self):
        self.toolframe()
        self.listframe()
        self.mainloop()

# Class for adding a single URL
class AddURL(ctk.CTkToplevel):
    def __init__(self):
        super().__init__()
        self.iconbitmap(path)
        self.after(200, lambda: self.iconbitmap(path))
        self.geometry("300x100")
        self.attributes("-topmost", True)
        self.title("Add video")
        self.minsize(300, 100)
        ctk.CTkLabel(self, text="Enter video link or playlist link").pack()
        self.entry = ctk.CTkEntry(self)
        self.entry.pack(fill="x", padx=10, expand=True)
        button = ctk.CTkButton(self, text="add", fg_color="#222222", hover_color="gray", command=self.add, border_width=2)
        button.pack(expand=True)
    
    # Add the video or playlist
    def add(self):
        url = self.entry.get()
        try:
            YouTube(url)
            app.addvideo(url)
            self.destroy()
            return
        except:
            pass  
        try:
            playlist = Playlist(url)
            for video in playlist.videos:
                app.addvideo(video.watch_url)
            self.destroy()         
        except:
            CTkMessagebox(title="Error", icon="cancel", message="Invalid URL")
            self.destroy()
            return       

# Class for adding multiple links
class MultiLink(ctk.CTkToplevel):
    def __init__(self):
        super().__init__()
        self.iconbitmap(path)
        self.after(200, lambda: self.iconbitmap(path))
        self.geometry("600x400")
        self.attributes("-topmost", True)
        self.title("Add video")
        self.minsize(600, 400)
        self.text = ctk.CTkTextbox(self)
        self.text.pack(expand=True, fill="both")
        button = ctk.CTkButton(self, text="add", fg_color="#222222", hover_color="gray", command=self.add, border_width=2)
        button.pack()
    
    # Add multiple videos
    def add(self):
        url = self.text.get("1.0", ctk.END)
        url = url.split("\n")
        for i in url:
            try:
                YouTube(i)
                app.addvideo(i)
            except:
                pass
        self.destroy()       

# Main entry point
if __name__ == "__main__":
    ctk.set_appearance_mode("dark")
    app = YoutubeDownloader()
    app.run()
